name: CD
on:
  push:
    branches: [master]
env:
  TF_BACKEND_BUCKET: ${{ secrets.tf_backend_bucket }}
  TF_BACKEND_ACCESS_KEY: ${{ secrets.tf_backend_access_key }}
  TF_BACKEND_SECRET_KEY: ${{ secrets.tf_backend_secret_key }}
  TF_VAR_client_id: ${{ secrets.azure_client_id }}
  TF_VAR_client_secret: ${{ secrets.azure_client_secret }}
  TF_VAR_subscription_id: ${{ secrets.azure_subscription_id }}
  TF_VAR_tenant_id: ${{ secrets.azure_tenant_id }}
  TF_VAR_digitalocean_token: ${{ secrets.digitalocean_token }}
  TF_VAR_digitalocean_spaces_key: ${{ secrets.digitalocean_spaces_key }}
  TF_VAR_digitalocean_spaces_secret_key: ${{ secrets.digitalocean_spaces_secret_key }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Terraform format
        run: terraform fmt -check infra
      - name: Terraform init
        run: |
          terraform init --input=false \
            -backend-config "bucket=$TF_BACKEND_BUCKET" \
            -backend-config "access_key=$TF_BACKEND_ACCESS_KEY" \
            -backend-config "secret_key=$TF_BACKEND_SECRET_KEY" \
            infra
      - name: Terraform plan
        run: terraform plan --out=tfplan --input=false infra
      - name: Terraform apply
        run: terraform apply --input=false tfplan
