name: CD
on:
  push:
    branches: [master]
env:
  TF_BACKEND_BUCKET: ${{ secrets.tf_backend_bucket }}
  TF_BACKEND_ACCESS_KEY: ${{ secrets.tf_backend_access_key }}
  TF_BACKEND_SECRET_KEY: ${{ secrets.tf_backend_secret_key }}
  TF_VAR_client_id: ${{ secrets.azure_client_id }}
  TF_VAR_client_secret: ${{ secrets.azure_client_secret }}
  TF_VAR_subscription_id: ${{ secrets.azure_subscription_id }}
  TF_VAR_tenant_id: ${{ secrets.azure_tenant_id }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Terraform format
        run: terraform fmt infra -check
      - name: Terraform init
        run: |
          terraform init infra --input=false \
            -backend-config "bucket=$TF_BACKEND_BUCKET" \
            -backend-config "access_key=$TF_BACKEND_ACCESS_KEY" \
            -backend-config "secret_key=$TF_BACKEND_SECRET_KEY"
      - name: Terraform plan
        run: terraform plan infra --out=tfplan --input=false
      - name: Terraform apply
        run: terraform apply tfplan --input=false
